library(plyr)
library(dplyr)
activity_labels <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/activity_labels.txt", col.names = c("actlabels", "actnames"))
str(activity_labels)
features <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/features.txt")
str(features)
features_names <- as.vector(features$V2)
str(features_names)
Y_test <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/test/Y_test.txt", col.names = "actlabels")
str(Y_test)
X_test <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/test/X_test.txt", col.names = features_names)
str(X_test)
subject_test <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/test/subject_test.txt", col.names = "subject")
str(subject_test)
Y_train <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/train/Y_train.txt", col.names = "actlabels")
str(Y_train)
X_train <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/train/X_train.txt", col.names = features_names)
str(X_train)
subject_train <- read.table("C:/Users/Sam/Documents/CD_Dataset/UCIHARDataset/train/subject_train.txt", col.names = "subject")
str(subject_train)
X_test <- cbind(subject_test, Y_test, X_test)
X_train <- cbind(subject_train, Y_train, X_train)
Test_And_Train_Data <- rbind(X_test, X_train)
Test_And_Train_Data <- join(x = Test_And_Train_Data, y = activity_labels, by = "actlabels")
All_Cols <- names(Test_And_Train_Data)
Selected_Cols <- grep("mean[^F]|std", All_Cols, value = TRUE)
Test_And_Train_Data_Trim <- select(Test_And_Train_Data, c("subject", "actlabels", "actnames", Selected_Cols))
Avg_ByActSub <- Test_And_Train_Data_Trim %>% group_by(subject, actnames) %>% summarise_all("mean") %>% arrange(subject, actlabels)
